### ISSUE TITLE
Attribute Consumer Service: error handling 

### ISSUE THREAD

**Issue by rgaudenzi-fub** [fondazionebordoni/spid-django#7]
Currently, the attribute_consumer view just raises an HttpResponseServerError when an error occurs (e.g., InResponseTo field check failure, a manual GET from the browser, ...).
The idea is to redirect the user to an error page showing a message explaining to the user that something went wrong. 
Moreover, we'd like to list the error data when DEBUG is True, for developing purposes.

**Comment by ewedlund** [comment]
Resolved in ??
